version: '3'

services:
  votacao-service-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - DATABASE_HOST=votacaodb.ccgokeix6ea5.us-east-1.rds.amazonaws.com
      - DATABASE_PORT=5432
      - DATABASE_NAME=votacaodb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=28032017
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
